# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecdecc8e9605d8d3ec16e46eadfe5e823c493f0b659ebf6434a1992c531c98c6079791f278b9e7a3788a945296faed4c304514ad6bd8eed01b81487e995633f7

test:
  secret_key_base: f8ed13447cfe95aed89aa8ee5a16dc589a9a6f9a286b7a16522500b8898a1900b63dc85315fefd8654db584348e7fe3bfb04c640e6b2e478ccef8e399db3433f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
